### PR TITLE
improve handling of #WithComments

### PR DESCRIPTION
**Pull request by toby-jn**
I had some issues with gosaml2 when the IdP was using the `http://www.w3.org/2001/10/xml-exc-c14n#WithComments` canonicalization algorithm. According to the [SAML 2.0 spec](https://docs.oasis-open.org/security/saml/v2.0/saml-metadata-2.0-os.pdf):

> SAML implementations SHOULD use Exclusive Canonicalization, with or without comments

So these should be handled by goxmldsig in order to support SAML correctly.

I also noticed that the existing canonicalization algorithms were not removing comments when transforming the XML in the cases that didn't have `#WithComments`.

This change extends the existing canonicalizers to include a comments flag, which will strip comments if not set, and adds additional `AlgorithmID`s for each of the `#WithComments` variants.

### CODE REVIEW

**Comment by toby-jn** [comment]
Hi @russellhaering any chance this could be considered for merge?

**Comment by gerritmaritz** [comment]
+1 Also facing issues with an IdP that is using the `WithComments` variant. I see there is another PR open so this is probably affecting several consumers: https://github.com/russellhaering/goxmldsig/pull/74

**Comment by sahnib** [comment]
+1. Facing similar issues for IdP using `WithComments` variant.

**Comment by simonbrynych** [comment]
@russellhaering this PR seems good to me and it's definitely worth merging it. I'm struggling withComments too.

**Comment by tomstaijen** [comment]
+1

**Comment by lejeuneretif** [comment]
+1 That would help a ton of people.

**Comment by CoryBond** [comment]
+1

**Comment by alolita** [comment]
@russellhaering please let us know how we can help you merge this PR? We are blocked on using this library and would greatly appreciate a response from you. Thanks in advance.

**Comment by russellhaering** [comment]
Thanks for your work on this, sorry it has taken me so (very) long to get around to looking at it!

**Comment by toby-jn** [comment]
no problem, thanks for taking the time to look :pray:

**Pull request merged**
