### PR TITLE
Work In Progress: Structured Signature Refactor

### PR DESCRIPTION
**Pull request by russellhaering**
So far this is working, but not yet finished.

The idea is to unmarshal Signatures into a structured object as early as possible in order to keep later access to signature information clear and safe.

### CODE REVIEW

**Comment by russellhaering** [comment]
@arun251 I'm not totally happy with the factoring of 872fe2f, but I think it is working. It makes the test case for Oracle Access Manager work too.

Can you verify this against the Okta tool?

**Comment by russellhaering** [comment]
I take that back, this fixed some issues but introduced a few new ones. Getting much closer though.

**Comment by arun251** [comment]
Agreed, it does seem to fix my test in #21 but also introduces failures in `gosaml2`.

**Comment by russellhaering** [comment]
@arun251 can you give this a shot now? All the tests pass here, and the gosaml2 tests will pass once I merge this: https://github.com/russellhaering/gosaml2/commits/russell_h/oam_works

**Comment by russellhaering** [comment]
This seems to be working as expected and fixes a number of known issues.

**Comment by arun251** [comment]
Sorry for not responding much sooner. With the latest `master` revisions in both `gosaml2` and `goxmldsig`, I see a number of regressions at http://saml.oktadev.com/, mostly along the lines of modified SAML responses not being rejected. I suspect #23 is tracking this, so I'll follow that issue for updates.

**Comment by arun251** [comment]
I raised these regressions as #25 since #23 is closed and didn't resolve them.

**Pull request merged**
